1682257208

diff --git a/zsh/aliases b/zsh/aliases
--- a/zsh/aliases
+++ b/zsh/aliases
@@ -4,7 +4,6 @@ alias -g M="| $__LESS"
 alias -g Y="| gpaste"
 alias -g H='ansifilter --html -eUTF8'
 
-#alias **="$(fzf)"
 alias ...="../../"
 alias ....="../../../"
 alias cs="history -i 0"
@@ -16,41 +15,24 @@ alias cp="cp -a"
 alias rm="rm -I"
 alias at="at -m"
 alias ow="$__SUDO chown -R `whoami`:`whoami`"
-alias vin="vi --noplugin"
 alias mkd="mkd2html -footer \"<hr /> Last updated: `date +"%F %T%:z"`\""
 alias w3m="/usr/bin/w3m -no-graph"
 alias diff="$__DIFF"
 alias more="$__LESS"
 alias tree="LANG=c tree -C"
-alias grep="grep"
+alias grep="grep --color=always"
 alias egrep="egrep --color=always"
 alias scp="scp -p"
 alias lintian="lintian -viI"
 alias tig="tig --all"
-alias sudo="/usr/bin/sudo -E"
+alias rsync="rsync -C"
+alias sudo="/usr/bin/sudo "
 alias anki="/usr/bin/anki -b ~/.anki"
 alias rot13="tr a-zA-Z n-za-mN-ZA-M"
 alias atf-run="env -i PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/atf/bin atf-run"
 alias guanji="sudo systemctl poweroff"
 alias chongqi="sudo systemctl reboot"
 alias percol="percol --match-method=pinyin"
-alias fs="ffsend upload -c"
-alias puml="java -jar /opt/plantuml/plantuml.jar"
-alias cnpm="npm --registry=https://registry.npm.taobao.org \
-    --cache=$HOME/.npm/.cache/cnpm \
-    --disturl=https://npm.taobao.org/dist \
-    --userconfig=$HOME/.cnpmrc"
-alias docker="sudo docker"
-
-alias g="git"
-alias gll="git ll"
-alias gls="git ls"
-alias gst="git st"
-alias gdi="git di"
-alias gci="git ci"
-alias gco="git co"
-alias gup="git pull"
-alias gpu="git push"
 
 cd() {
     if [[ "$@" == "." ]]; then
@@ -170,7 +152,7 @@ piff() {
 
 # package {{{
 DISTRO=`awk '/[a-zA-Z]/ { print $1; exit }' /etc/issue`
-if [[ $DISTRO == "Debian" || $DISTRO == "Ubuntu" ]]; then
+if [[ $DISTRO == "Debian" || $DISTRO == "Ubuntu" || $DISTRO == "Kali" ]]; then
     alias api="$__SUDO apt-get install"
     alias apo="apt-get source"
     alias ape="vi /etc/apt/sources.list"
@@ -255,7 +237,7 @@ doG() {
 alias pu="python $TODO_DIR/opt/punch/Punch.py"
 alias td="todo.sh"
 alias tda="todo.sh add"
-alias tdr="todo.sh del"
+#alias tdr="todo.sh del"
 alias tdR="todo.sh replace"
 alias td0="todo.sh prepend"
 alias td\$="todo.sh append"
@@ -274,14 +256,38 @@ tdc() {
         td$ ${1} "/* ${(@)argv[2,$#]} */" > /dev/null 2>&1
     fi
 }
+tdr() { # remember the milk
+# depends: http://www.davidwaring.net/projects/rtm.html
+# depends: http://www.rememberthemilk.com/
+    idx=${1}
+    if [[ ${idx} == "" ]]; then
+        return
+    fi
+    inbox=$(echo "#0x5BCC0x58EB0x901A" | ascii2uni -q)
+
+    rem=$(remind -s+4 $TODO_DIR/var/remind/index.rem | sed -n "${idx}p")
+    rem_date=$(echo ${rem} | sed 's/\(^.\{10\}\).*/\1/' )
+    rem_time=$(echo ${rem} | sed 's/.* \([0-9]\{1,2\}:[0-9]\{1,2\}[ap]m\) .*/\1/')
+    rem_mesg=$(echo ${rem} | sed 's/.*\(\([ap]m\)\|\(\*\)\) \(.*\)/\4/g')
+
+    if [[ ${rem_time} == ${rem} ]]; then # 没有时间信息
+        rem_time=""
+    fi
+
+    if ! pgrep "python" | grep "rtm add"; then # todo
+        (rtm add ${inbox} "${rem_date} ${rem_time} ${rem_mesg}" > /dev/null &)
+    else
+        echo "rtm: there is another running instance."
+    fi
+}
 tde() {
     if [ -z ${1} ]; then
         loc=":normal M"
     else
         loc=":normal $1gg"
     fi
-    HOME_FILE="$TODO_DIR/var/home/todo.log"
-    WORK_FILE="$TODO_DIR/var/work/todo.log"
+    A_FILE="$TODO_DIR/var/$TD/todo.log"
+    B_FILE="$TODO_DIR/var/work/todo.log"
     vi +":e $HOME_FILE" +":normal zz" \
         +":vs $WORK_FILE" +"${loc}"
 }
@@ -353,9 +359,9 @@ tdd() { # 完成一项工作
         fi
     fi
 }
-tdy() { # 过去完成一项工作
+tdD() { # 过去完成一项工作
     if [ -z ${2} ]; then # 如果没给参数，代表昨天完成
-        WHEN="yesterday"
+        WHEN="1 day ago"
     else
         WHEN=${2/da/days ago}
     fi
@@ -366,33 +372,31 @@ tdy() { # 过去完成一项工作
 # archive {{{
 tgz() {
     name=`echo $1 | sed 's/\/*$//g'`
-    tar -zcf "$name.tgz" $@
+    tar -zcf "$name.tar.gz" $@
 }
-tgzz() {
+tbz() {
     name=`echo $1 | sed 's/\/*$//g'`
-    tar -zcf "$name.tgz" $@ --exclude=.cscope --exclude-vcs
+    tar -jcf "$name.tar.bz2" $@
 }
-tgx() {
-    $__SUDO tar -zxvf $@
+txz() {
+    name=`echo $1 | sed 's/\/*$//g'`
+    tar -Jcf "$name.tar.xz" $@
 }
-tgg() {
-    tar -tf $@
+tzz() {
+    name=`echo $1 | sed 's/\/*$//g'`
+    tar --zstd -cf "$name.tar.zstd" $@
 }
 
-tjz() {
-    name=`echo $1 | sed 's/\/*$//g'`
-    tar -jcf "$name.tbz" $@
-}
-tjzz() {
-    name=`echo $1 | sed 's/\/*$//g'`
-    tar -jcf "$name.tbz" $@ --exclude=.cscope --exclude-vcs
-}
-tjx() {
-    $__SUDO tar -jxvf $@
-}
-tjg() {
-    tar -tf $@
-}
+tgg() { tar -ztf $@ }
+tbg() { tar -jtf $@ }
+txg() { tar -Jtf $@ }
+tzg() { tar --zstd -tf $@ }
+
+tgx() { $__SUDO tar -zxvf $@ }
+tbx() { $__SUDO tar -jxvf $@ }
+txx() { $__SUDO tar -Jxvf $@ }
+tzx() { $__SUDO tar --zstd -xvf $@ }
+
 # }}}
 
 # file {{{
@@ -416,7 +420,6 @@ alias -s xls=c_xls
 alias -s pdf="zathura"
 alias -s html=c_htm
 
-# 查看图片、同时复制到剪贴板
 c_png() { pqiv -i "$1" && copyq write image/png - < "$1" && copyq select 0 }
 c_jpg() { pqiv -i "$1" && copyq write image/jpg - < "$1" && copyq select 0 }
 c_gif() { pqiv -i "$1" && copyq write image/gif - < "$1" && copyq select 0 }
@@ -435,30 +438,60 @@ ghash() {
     echo -n $* | shasum | /bin/grep -Eo '[a-f].{4}' | head -1
 }
 
-D() {
-    src=$(echo $* | sed 's/\s*->\s*/->/' | /bin/grep -Po '^((?!->).)*')
-    dst=$(echo $* | sed 's/\s*->\s*/->/' | /bin/grep -Po '(?<=->).*$')
-
-    src_ip=${src%%:*}
-    dst_ip=${dst%%:*}
-
-    src_path=${src#*:}
-    dst_path=${dst#*:}
-
-    src_clsync="$src_path"
-    dst_clsync="user@$dst_ip::$(ghash $dst_path)"
-
-    echo "$(ghash $src_clsync)-$(ghash $dst_clsync)" | grep -o '.*'
-}
-
 # }}}
 
-# fzf {{{
-all() {
-    local all raw
-    all=/sun/worktop/ansible/inventory/all
-    on=$(/bin/grep -f =(ansible -u root 'all:!off' --list-hosts | awk '{print $1}') $all | sed 's/\(.*\)\s.*=\(.*\)/\1 \2/')
-    echo $on | fzf -0 -1 --preview-window=hidden
+# golang {{{
+# https://gist.github.com/nikhita/432436d570b89cab172dcf2894465753#gistcomment-3038158
+goupgrade() {
+    export https_proxy=http://localhost:8123
+    release=$(curl --silent https://golang.org/doc/devel/release.html | /bin/grep -Eo 'go[0-9]+(\.[0-9]+)+' | sort -V | uniq | tail -1)
+    os=$(uname -s | tr '[:upper:]' '[:lower:]')
+    arch=$(case "$(uname -m)" in i*) echo '386' ;; x*) echo 'amd64' ;; *) echo 'armv61'; esac)
+
+    dest="/opt/$release" && sudo mkdir -p "$dest"
+    curl --silent https://storage.googleapis.com/golang/$release.$os-$arch.tar.gz | sudo tar -zxv --strip-components 1 -C $dest
+    sudo ln -sfn "$dest" /opt/go
+    echo "updated to $(go version)"
+}
+# }}}
+
+nnn-preview () {
+    # Block nesting of nnn in subshells
+    if [ -n "$NNNLVL" ] && [ "${NNNLVL:-0}" -ge 1 ]; then
+        echo "nnn is already running"
+        return
+    fi
+
+    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
+    # If NNN_TMPFILE is set to a custom path, it must be exported for nnn to see.
+    # To cd on quit only on ^G, remove the "export" and set NNN_TMPFILE *exactly* as this:
+    #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
+    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
+
+    # This will create a fifo where all nnn selections will be written to
+    NNN_FIFO="$(mktemp --suffix=-nnn -u)"
+    export NNN_FIFO
+    (umask 077; mkfifo "$NNN_FIFO")
+
+    # Preview command
+    preview_cmd="/tmp/foo.sh"
+
+    # Use `tmux` split as preview
+    if [ -e "${TMUX%%,*}" ]; then
+        tmux split-window -e "NNN_FIFO=$NNN_FIFO" -dh "$preview_cmd"
+
+    # Use `xterm` as a preview window
+    elif (which xterm &> /dev/null); then
+        xterm -e "$preview_cmd" &
+
+    # Unable to find a program to use as a preview window
+    else
+        echo "unable to open preview, please install tmux or xterm"
+    fi
+
+    nnn "$@"
+
+    rm -f "$NNN_FIFO"
 }
 # }}}
 
